### ISSUE TITLE
sogou translator return just hash password

### ISSUE THREAD

**Issue by noman00910** [UlionTse/translators#32]
Sogou translator returns just the password. Is there a way to decrypt it or to get an exact translation instead of a password?

**Comment by UlionTse** [comment]
Please tell me the version of translator. if your version <4.7.15, upgrade it.

发自我的华为手机


-------- 原始邮件 --------
发件人： noman00910 <notifications@github.com>
日期： 2021年2月15日周一 19:22
收件人： UlionTse/translators <translators@noreply.github.com>
抄送： Subscribed <subscribed@noreply.github.com>
主 题： [UlionTse/translators] sogou translator return just hash password (#32)

Sogou translator returns just the password. Is there a way to decrypt it or to get an exact translation instead of a password?

―
